// Mock data with detailed product information
export const products = [
  {
    name: "Wireless Headphones",
    price: 2999,
    image: "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1326",
    description: "Premium wireless headphones with active noise cancellation and 30-hour battery life. Perfect for music lovers and professionals.",
    category: "Audio",
    stock: 45,
    rating: 4.7,
    reviews: 328,
    specifications: {
      brand: "SoundMax",
      color: "Black",
      weight: "250g",
      warranty: "2 Years",
    },
    features: [
      "Active Noise Cancellation",
      "30-hour Battery Life",
      "Bluetooth 5.0",
      "Quick Charge (5 min = 2 hours)",
      "Built-in Microphone",
      "Comfortable Over-ear Design",
      "Foldable Design",
    ],
  },
  {
    name: "Smart Watch",
    price: 4999,
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1172",
    description: "Advanced smartwatch with health tracking, fitness modes, and AMOLED display. Monitor your health 24/7.",
    category: "Wearables",
    stock: 32,
    rating: 4.6,
    reviews: 215,
    specifications: {
      brand: "TechBrand",
      color: "Silver",
      weight: "180g",
      warranty: "1 Year",
    },
    features: [
      "Heart Rate Monitor",
      "Sleep Tracking",
      "GPS Navigation",
      "50+ Fitness Modes",
      "Water Resistant (50m)",
      "AMOLED Display",
      "7-day Battery Life",
      "Blood Oxygen Monitor",
    ],
  },
  {
    name: "Bluetooth Speaker",
    price: 1999,
    image: "https://images.unsplash.com/photo-1589001181560-a8df1800e501?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1074",
    description: "Portable Bluetooth speaker with 360-degree sound and IPX7 waterproof rating. Perfect for outdoor adventures.",
    category: "Audio",
    stock: 58,
    rating: 4.5,
    reviews: 412,
    specifications: {
      brand: "SoundMax",
      color: "Blue",
      weight: "650g",
      warranty: "1 Year",
    },
    features: [
      "360-Degree Sound",
      "IPX7 Waterproof",
      "24-hour Battery Life",
      "Bluetooth 5.0",
      "Bass Boost Technology",
      "TWS (True Wireless Stereo)",
      "Mic for Calls",
    ],
  },
  {
    name: "Gaming Mouse",
    price: 1499,
    image: "https://images.unsplash.com/photo-1629429408209-1f912961dbd8?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170",
    description: "Professional gaming mouse with precision tracking and customizable buttons. Designed for competitive gaming.",
    category: "Peripherals",
    stock: 67,
    rating: 4.8,
    reviews: 543,
    specifications: {
      brand: "GamingPro",
      color: "Black",
      weight: "95g",
      warranty: "2 Years",
    },
    features: [
      "8000 DPI Sensor",
      "Programmable 7 Buttons",
      "RGB Lighting",
      "USB Wired Connection",
      "Ergonomic Design",
      "Polling Rate 1000Hz",
      "Lightweight Design",
    ],
  },
  {
    name: "Keyboard",
    price: 999,
    image: "https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=686",
    description: "Mechanical gaming keyboard with customizable RGB lighting and hot-swappable switches.",
    category: "Peripherals",
    stock: 41,
    rating: 4.6,
    reviews: 287,
    specifications: {
      brand: "TechMech",
      color: "Black",
      weight: "920g",
      warranty: "2 Years",
    },
    features: [
      "Mechanical Switches",
      "RGB Lighting",
      "Hot-swappable Keys",
      "Programmable Keys",
      "Aluminum Frame",
      "USB Wired Connection",
      "Media Controls",
    ],
  },
  {
    name: "USB-C Charger",
    price: 1299,
    image: "https://images.unsplash.com/photo-1595756630452-736bc8ef3693?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170",
    description: "Fast charging USB-C charger compatible with all devices. 65W power delivery with multiple ports.",
    category: "Chargers",
    stock: 89,
    rating: 4.4,
    reviews: 156,
    specifications: {
      brand: "PowerTech",
      color: "White",
      weight: "180g",
      warranty: "1 Year",
    },
    features: [
      "65W Power Delivery",
      "Dual USB-C Ports",
      "Fast Charging",
      "Compact Design",
      "Safety Certified",
      "Universal Compatibility",
      "LED Indicator",
    ],
  },
];
